/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enfermedadv2;

/**
 *
 * @author ACER
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    private int index=0;
    private String[] preguntas ={
        "¿Ha experimentado hinchazon o distension abdominal ?",
        "¿Tienes diarrea ?",
        "¿Tienes gases ?",
        "¿Ha sentido nauseas ?",
        "¿Ha tenido dolor en el abdomen ?",
        "¿Ha escuchando ruidos estomacales ?",
        "¿Tuvo vomito ?",
        "¿Ha sentido acidez estomacal ?",
        "¿Tiene dificultad al tragar ?",
        "¿Sufre de perdida de peso ?",
        "¿Sufre de perdida de apetito ?",
        "¿Ha notado heces con sangre ?",
        "¿Sufre de ictericia ?",
        "¿Se siente con fatiga ?",
        "¿Tiene dolor estomacal ?",
        "¿Ha notado estrechamiento de heces ?",
    };
    
    private String[] intolLactosa ={"hinchazon o distension abdominal","diarrea","gases","nauseas","dolor en el abdomen","ruidos estomacales","vomito"};
    private String[] cancerEstomago = {"nauseas","vomito","acidez estomacal","dificultad al tragar","perdida de peso","perdida de apetito","hinchazon o distension abdominal","heces con sangre","ictericia","fatiga","dolor estomacal"};
    private String [] cancerColon = {"diarrea","estrechamiento de heces","heces con sangre","dolor en el abdomen","fatiga","perdida de peso"};
    
    //Contadores para cada enfermedad
    private int contadorIntolLactosa = 0;
    private int contadorCancerEstomago = 0;
    private int contadorCancerColon = 0;
    
    public Pantalla() {
        initComponents();
        mostrarPregunta();
    }

    
    private void mostrarPregunta(){
        if(index<preguntas.length){
            jLabel2.setText(preguntas[index]);
        }else{
            //Mostramos resultado
            mostrarResultados();
        }
    };
    
    private void siguientePregunta(){
        index++;
        mostrarPregunta();
    };
    
    private void verificarSintoma(String respuesta){
        if (index >= preguntas.length) {
            return;
        }
        String preguntaAct = preguntas[index].toLowerCase();
        
        //Intolerancia Lactosa
        for (String sintoma : intolLactosa) {
            if (preguntaAct.contains(sintoma.toLowerCase()) && respuesta.equals("Sí")) {
                contadorIntolLactosa++;
                break;
            }
        }
        //Cancer Estomago
        for (String sintoma : cancerEstomago) {
            if (preguntaAct.contains(sintoma.toLowerCase()) && respuesta.equals("Sí")) {
                contadorCancerEstomago++;
                break;
            }
        }

        // Verificar si la pregunta contiene algún síntoma de cáncer de colon
        for (String sintoma : cancerColon) {
            if (preguntaAct.contains(sintoma.toLowerCase()) && respuesta.equals("Sí")) {
                contadorCancerColon++;
                break;
            }
        }
    };
    
    private void mostrarResultados() {
        String resultado = "<html>Resultados:<br>" +
                "Intolerancia a la lactosa: " + contadorIntolLactosa + " síntomas<br>" +
                "Cáncer de estómago: " + contadorCancerEstomago + " síntomas<br>" +
                "Cáncer de colon: " + contadorCancerColon + " síntomas<br><br>";

        // Determinar la enfermedad con más síntomas
        if (contadorIntolLactosa > contadorCancerEstomago && contadorIntolLactosa > contadorCancerColon) {
            resultado += "Posible diagnóstico: Intolerancia a la lactosa";
        } else if (contadorCancerEstomago > contadorIntolLactosa && contadorCancerEstomago > contadorCancerColon) {
            resultado += "Posible diagnóstico: Cáncer de estómago";
        } else if (contadorCancerColon > contadorIntolLactosa && contadorCancerColon > contadorCancerEstomago) {
            resultado += "Posible diagnóstico: Cáncer de colon";
        } else {
            resultado += "No se pudo determinar un diagnóstico claro.";
        }

        resultado += "</html>";
        jLabel2.setText(resultado); // Mostrar los resultados en jLabel2
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_si = new javax.swing.JButton();
        btn_no = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_rep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Diagnostico de enfermedades");

        btn_si.setText("Si");
        btn_si.setName(""); // NOI18N
        btn_si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siActionPerformed(evt);
            }
        });

        btn_no.setText("No");
        btn_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_noActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("jLabel2");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btn_rep.setText("Repetir");
        btn_rep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_repActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_si)
                        .addGap(90, 90, 90)
                        .addComponent(btn_no)
                        .addGap(112, 112, 112))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_rep)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_si)
                    .addComponent(btn_no))
                .addGap(82, 82, 82)
                .addComponent(btn_rep)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siActionPerformed
        // TODO add your handling code here:
        verificarSintoma("Sí");
        siguientePregunta();
    }//GEN-LAST:event_btn_siActionPerformed

    private void btn_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_noActionPerformed
        // TODO add your handling code here:
        siguientePregunta();
    }//GEN-LAST:event_btn_noActionPerformed

    private void btn_repActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_repActionPerformed
        // TODO add your handling code here:
        index = 0;
        contadorIntolLactosa = 0;
        contadorCancerEstomago = 0;
        contadorCancerColon = 0;
        mostrarPregunta();
    }//GEN-LAST:event_btn_repActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_no;
    private javax.swing.JButton btn_rep;
    private javax.swing.JButton btn_si;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
